@DbMilos.WebApi_HostAddress = https://api.dbmilos.com

POST {{DbMilos.WebApi_HostAddress}}/api/lists/listtransformer/transform
Content-Type: application/json
Accept: application/json

{
    "content": "coffee,ice cream,  milk",
    "separator": ",",
    "operation": "ToPascalCase",
    "trim":"true"
}
###
GET {{DbMilos.WebApi_HostAddress}}/api/lists/listtransformer/getoperations
Content-Type: application/json
Accept: application/json
###
